name: CI

on:
  pull_request: 
  push: 
    branches: 
      - main

jobs:
  build:

    strategy:
      matrix:
        node-version: ["21.x", "20.x"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
