name: CI

on:
  pull_request: 
  push: 
    branches: 
      - main

jobs:
  build:
    permissions: 
      pull-requests: write
    env:
      MAIN_VERSION: "21.x"

    strategy:
      matrix:
        node-version: ["21.x", "20.x"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Prepare coverage report in markdown
        uses: fingerprintjs/action-coverage-report-md@v2.0.1
        id: coverage
        with:
          textReportPath: coverage/coverage.txt

      - name: Add coverage commment to the PR
        uses: marocchino/sticky-pull-request-comment@v2.9.2
        with:
          message: ${{ steps.coverage.outputs.markdownReport }}

      - name: Add coverage report to the job summary
        run: |
          echo "## Code Coverage v${{ matrix.node-version }}" >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.coverage.outputs.markdownReport }}" >> "$GITHUB_STEP_SUMMARY"
